config/routes.rb
MoRevision::Application.routes.draw do
  get "books/codes"
  get "books/generate_code"
  root :to => redirect("/users/sign_in")
  
  resources :statuses
  
  get "qualifications/get_qualifications" => "qualifications#get_qualifications"
  
  devise_for :users, :controllers => {:registrations => "devise/registrations", :sessions => "devise/sessions", :passwords => "devise/passwords"}
  
  devise_scope :user do
  	get 'administrator' => 'devise/registrations#new', :as => :administrator_dashboard
  	get 'users' => 'devise/registrations#new'
  	get "user/edit_profile/:id" => "devise/registrations#edit", :as => :edit_user_profile
  	patch 'user/update_profile' => 'devise/registrations#update_profile', :as => :update_user_profile
  end
  get 'user/search' => 'users#search', :as => :search_user
  get 'user/enable_profile/:id' => 'users#enable_profile', :as => :enable_user_profile
  get 'user/disable_profile/:id' => 'users#disable_profile', :as => :disable_user_profile
  get 'user/update_profile' => 'devise/registrations#new'
  
  get "departments" => "departments#index"
  post "department/create" => "departments#create"
  get "editer-un-departement/:department_id" => "departments#edit"
  get "désactiver-un-departement/:department_id" => "departments#disable", :as => :disable_department
  get "activer-un-departement/:department_id" => "departments#enable", :as => :enable_department
  post "department/update" => "departments#update"
  get "department/update" => "departments#index"  
  
  post "qualification/create" => "qualifications#create"
  get "editer-une-qualification/:qualification_id" => "qualifications#edit"
  get "désactiver-une-qualification/:qualification_id" => "qualifications#disable", :as => :disable_qualification
  get "activer-une-qualification/:qualification_id" => "qualifications#enable", :as => :enable_qualification
  post "qualification/update" => "qualifications#update"
  get "qualification/update" => "departments#index"  
  
  get "categories" => "categories#index"
  post "category/create" => "categories#create"
  get "editer-un-type-de-document/:category_id" => "categories#edit"
  get "désactiver-un-type-de-document/:category_id" => "categories#disable", :as => :disable_category
  get "activer-un-type-de-document/:category_id" => "categories#enable", :as => :enable_category
  post "category/update" => "categories#update"
  get "category/update" => "categories#index" 
  
  get "shafts" => "shafts#index"
  post "shaft/create" => "shafts#create"
  get "editer-un-puits/:shaft_id" => "shafts#edit"
  get "désactiver-un-puits/:shaft_id" => "shafts#disable", :as => :disable_shaft
  get "activer-un-puits/:shaft_id" => "shafts#enable", :as => :enable_shaft
  post "shaft/update" => "shafts#update"
  get "shaft/update" => "shafts#index"

  get "blocks/get_blocks" => "blocks#get_blocks"  
  post "block/create" => "blocks#create"
  get "editer-un-bloc/:block_id" => "blocks#edit"
  get "désactiver-un-bloc/:block_id" => "blocks#disable", :as => :disable_block
  get "activer-un-bloc/:block_id" => "blocks#enable", :as => :enable_block
  post "block/update" => "blocks#update"
  get "block/update" => "blocks#index"
  
  get "consultants" => "consultants#index"
  post "consultant/create" => "consultants#create"
  get "editer-un-organe-detude/:consultant_id" => "consultants#edit"
  get "désactiver-un-organe-detude/:consultant_id" => "consultants#disable", :as => :disable_consultant
  get "activer-un-organe-detude/:consultant_id" => "consultants#enable", :as => :enable_consultant
  post "consultant/update" => "consultants#update"
  get "consultant/update" => "consultants#index"  
  
  get "boites-darchives" => "archive_boxes#index"
  post "archive_box/create" => "archive_boxes#create"
  get "editer-une-boite-darchive/:archive_box_id" => "archive_boxes#edit"
  get "désactiver-une-boite-darchive/:archive_box_id" => "archive_boxes#disable", :as => :disable_archive_box
  get "activer-une-boite-darchive/:archive_box_id" => "archive_boxes#enable", :as => :enable_archive_box
  post "archive-box/update" => "archive_boxes#update"
  get "archive-box/update" => "archive_boxes#index"  
  
  get "creer-un-document-et-generer-son-code" => "books#codes", as: :generate_code
  post "books/search-available-books" => "books#search"
  post "recherche-parmis-tous-les-documents" => "books#search_all_books"
  post "books/search-unavailable-books" => "reservations#search_unavailable"
  post "book/create" => "books#create"
  get "book/create" => "books#codes"
  get "books/process_request" => "books#process_request", as: :process_request
  get "book/view-only" => "books#view_only", as: :only_view_book
  get "liste-des-documents-par-categorie" => "books#list", as: :list_books
  get "liste-des-documents-par-categorie/:category_id" => "books#list_books_per_category", as: :list_books_in_category
  get "telecharger-le-code-barre/:code" => "books#download_barcode", as: :download_barcode
 
  get "nouvelle-demande-de-documents" => "books#send_request", as: :lv_dashboard  
  get "nouvelle-demande-de-documents" => "books#send_request", as: :cd_dashboard  
  get "nouvelle-demande-de-documents" => "books#send_request", as: :cd_bd_dashboard
  get "nouvelle-demande-de-documents" => "books#send_request", as: :csadp_bd_dashboard 
  get "documents-en-attente-de-retrait" => "demands#agc_validated", as: :agc_dashboard
  get "pe/liste-des-documents-par-categorie" => "books#list", as: :pe_dashboard
  get "book/new_request" => "books#send_request", as: :new_book_request
  get "editer-les-informations-du-document/:book_id" => "books#edit", as: :edit_book
  post "book/update" => "books#update"
  get "book/update" => "books#codes"
  get "activer-un-document/:book_id" => "books#enable_book", as: :enable_book
  get "desactiver-un-document/:book_id" => "books#disable_book", as: :disable_book
  
  get "demands/history" => "demands#history", as: :demands_history
  get "csadp/demandes-en-attente-de-validation" => "demands#csadp_bd_on_hold", as: :csadp_bd_demands_on_hold
  get "demandes-en-attente-de-validation" => "demands#lv_on_hold", as: :lv_demands_on_hold
  get "demandes-validees" => "demands#lv_validated", as: :lv_demands_validated
  get "demands/statistics" => "demands#statistics", as: :demands_statistics
  get "documents-a-retirer" => "demands#to_get_back", as: :lv_demands_to_get_back  
  get "csadp/demands/to_get_back" => "demands#csadp_bd_to_get_back", as: :csadp_bd_demands_to_get_back
  get "documents-en-attente-de-retrait" => "demands#agc_validated", as: :agc_validated_demands
  get "agc/documents-a-rendre" => "demands#agc_to_return", as: :agc_demands_to_return
  get "agc/brought_back" => "demands#agc_brought_back"
  get "agc/damaged" => "demands#agc_damaged"
  get "agc/partial_return" => "demands#agc_partial_return"
  get "agc/partial_damage" => "demands#agc_partial_damage"
  get "demands/global_validation" => "demands#global_validation"
  get "demands/global_rejection" => "demands#global_rejection"
  get "demands/lv_global_validation" => "demands#lv_global_validation"
  get "demands/lv_global_rejection" => "demands#lv_global_rejection"
  get "demands/agc_global_validation" => "demands#agc_global_validation"
  get "demands/agc_global_rejection" => "demands#agc_global_rejection"
  get "demands/agc_partial_validation" => "demands#agc_partial_validation"
  get "demands/agc_partial_rejection" => "demands#agc_partial_rejection"
  get "demands/global_demand_status" => "demands#global_demand_status"
  get "demands/partial_validation" => "demands#partial_validation"
  get "demands/partial_rejection" => "demands#partial_rejection"
  get "demands/lv_partial_validation" => "demands#lv_partial_validation"
  get "demands/lv_partial_rejection" => "demands#lv_partial_rejection"
  get "documents-a-rendre" => "demands#lv_to_bring_back", as: :lv_demands_to_bring_back
  get "lv/demands/lv_bring_back" => "demands#lv_bring_back"
  get "lv/demands/lv_damaged" => "demands#lv_damaged"
  get "lv/demands/partial_return" => "demands#lv_partial_return"
  get "lv/demands/partial_damage" => "demands#lv_partial_damage"
  get "demands/partial_demand_status" => "demands#partial_demand_status"
  
  get "agc_demands/history" => "demands#agc_history", as: :agc_demands_history
  
  get "liste-des-agents-du-centre" => "cdbd#list_library_agents", as: :list_library_agents
  get "donner-le-droit-de-validation/:id" => "cdbd#give_validation_right", as: :give_validation_right
  get "retirer-le-droit-de-validation/:id" => "cdbd#remove_validation_right", as: :remove_validation_right
  
  get "nouvelle-reservation-de-documents" => "reservations#index", as: :reservations
  get "reservation/create" => "reservations#create"
  get "liste-des-reservations-de-documents" => "reservations#list", as: :list_reservations
  
  get "rapports-generaux-de-demandes-de-documents" => "reports#global_reports", as: :global_reports
  get "rapports-personnels-de-demandes-de-documents" => "reports#personnal_reports", as: :personnal_reports
  get "historique-personnel-des-demandes-de-documents" => "reports#personnal_reports_history", as: :personnal_reports_history
  get "historique-personnel-de-la-liste-des-demandes-de-documents" => "reports#personnal_demands", as: :personnal_demands_list
  get "historique-des-demandes-de-documents-rejetees" => "reports#personnal_rejected_demands", as: :personnal_rejected_demands
  get "liste-des-documents-constituant-la-demande/:id" => "reports#list_documents_in_demand", as: :personnal_demand_documents_list  
  
  get "historique/demandes-en-attente/liste-par-qualification" => "reports#departments_on_hold", as: :demands_on_hold_per_qualification
  get "historique/demandes-en-attente/liste-des-utilisateurs/:qualification_id" => "reports#list_users_on_hold", as: :users_on_hold_demands_per_qualification
  get "historique/demandes-en-attente/liste-des-demandes/:user_id" => "reports#demands_on_hold", as: :demands_on_hold_report
  

app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, value| %>    
  <%# if value.eql?(true) %>
    <div class="<%= flash_class(key) %> fade in">      
      <%= value %>
    </div>
  <%# end %>
<% end %>

app/views/layouts/administrator.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Arci || <%= current_user.short_profile %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    "stylesheets", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    "jquery.bubblepopup.v2.3.1", media: "all", "data-turbolinks-track" => true %>
  
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag :defaults %>
  <%= javascript_include_tag "plugins/jquery/jquery-1.9.1.min", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "plugins/jquery/jquery-ui-1.10.1.custom.min", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "jquery.easing", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "jquery.collapse", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "jquery.bubblepopup.v2.3.1.min", "data-turbolinks-track" => true %>
  
  <%= javascript_include_tag "plugins/jquery/jquery-migrate-1.1.1.min", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "plugins/jquery/globalize", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "plugins/other/excanvas", "data-turbolinks-track" => true %>
  
  <%= javascript_include_tag "plugins/other/jquery.mousewheel.min", "data-turbolinks-track" => true %>
  
  <%= javascript_include_tag "plugins/bootstrap/bootstrap.min", "data-turbolinks-track" => true %>    
  
  <%= javascript_include_tag "plugins/cookies/jquery.cookies.2.2.0.min", "data-turbolinks-track" => true %>  
  
  <%#= javascript_include_tag "plugins/animatedprogressbar/animated_progressbar", "data-turbolinks-track" => true %>
  <%#= javascript_include_tag "plugins/jflot/jquery.flot", "data-turbolinks-track" => true %>
  <%#= javascript_include_tag "plugins/jflot/jquery.flot.stack", "data-turbolinks-track" => true %>
  <%#= javascript_include_tag "plugins/jflot/jquery.flot.pie", "data-turbolinks-track" => true %>
  
  <%#= javascript_include_tag "plugins/sparklines/jquery.sparkline.min", "data-turbolinks-track" => true %>
  
  <%= javascript_include_tag "plugins/mcustomscrollbar/jquery.mCustomScrollbar.min", "data-turbolinks-track" => true %>
  
  <%= javascript_include_tag "plugins/uniform/jquery.uniform.min", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "plugins/select/select2.min", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "plugins/tagsinput/jquery.tagsinput.min", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "plugins/maskedinput/jquery.maskedinput-1.3.min", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "plugins/multiselect/jquery.multi-select.min", "data-turbolinks-track" => true %>
  
  <%= javascript_include_tag "plugins/shbrush/XRegExp", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "plugins/shbrush/shCore", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "plugins/shbrush/shBrushXml", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "plugins/shbrush/shBrushJScript", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "plugins/shbrush/shBrushCss", "data-turbolinks-track" => true %>   
  
  <%= javascript_include_tag "plugins", "data-turbolinks-track" => true %> 
  <%= javascript_include_tag "charts", "data-turbolinks-track" => true %> 
  
  <%= javascript_include_tag "actions", "data-turbolinks-track" => true %> 
  
  <%= csrf_meta_tags %>
</head>

<body>
	<div class = "wrapper">
	
		<!------------------------------------------ Sidebar ----------------------------------->
		<div class = "sidebar">		
			<div class="top">
		    <span class="petroci_logo"></span>
		  </div>
		  <div class="nContainer">                
        <ul class="navigation bordered">         
          <li class="active"><%= link_to "Dashboard", administrator_dashboard_path, class: "blblue" %></li>
          <li class="active"><%= link_to "Départements", "/departments", class: "blyellow" %></li>
          <li>
            <%= link_to "Paramètres", "#", class: "blgreen" %>
            <div class="open"></div>
            <ul>
              <li><%= link_to "Types de documents", "/categories" %></li>
              <li><%= link_to "Puits", "/shafts" %></li>
              <li><%= link_to "Organes d'étude", "/consultants" %></li>
              <li><%= link_to "B~A", "/boites-darchives" %></li>
            </ul>
          </li>
          <li class="active"><%= link_to "Documents", generate_code_path, class: "bldblue" %></li><!--
          <li>
            <a href="#" class="blgreen">News</a>
            <div class="open"></div>
            <ul>
              <li><%= link_to "Envoi", "#" %></li>
		          <li><%= link_to "Historique", "#" %></li>
		          <li><%= link_to "Statistiques", "#" %></li>
            </ul>
          </li>
                          
          <li>
            <a href="#" class="bldblue">Abonnés</a>
            <div class="open"></div>
            <ul>
              <li><a href="tables.html">Suspendre</a></li>
              <li><a href="tables_dynamic.html">Rechercher</a></li>                  
            </ul>
          </li>
          <li><a href="statistic.html" class="blred">Paramètres</a></li>  -->                    
        </ul>
        <a class="close">
          <span class="ico-remove"></span>
        </a>
    	</div>		  
		</div>
		<!------------------------------------------ Sidebar ----------------------------------->
		
		<!------------------------------------------ Body ----------------------------------->
		<div class = "body">
		
			<!------------------------------------------ Navigation ----------------------------------->
			<ul class="navigation">
        <li>
          <a href="<%= administrator_dashboard_path %>" class="button">
            <div class="icon">
              <span class="ico-monitor"></span>
            </div>                    
            <div class="name">Dashboard</div>
          </a>                
        </li>
        <li>
          <a href="/departments" class="button yellow">
            <!--<div class="arrow"></div>-->
            <div class="icon">
              <span class="ico-th-large"></span>
            </div>                    
            <div class="name">Départements</div>
          </a>          
        </li> 
        <li>
          <a href="#" class="button green">
            <div class="arrow"></div>
            <div class="icon">
              <span class="ico-book"></span>
            </div>
            <div class="name">Paramètres</div>
          </a>
          <ul class="sub">
            <li><%= link_to "Types de documents", "/categories" %></li>
            <li><%= link_to "Puits", "/shafts" %></li>
            <li><%= link_to "Organes d'étude", "/consultants" %></li>
            <li><%= link_to "B~A", "/boites-darchives" %></li>
          </ul>
        </li>
        <li>
          <a href="<%= generate_code_path %>" class="button dblue">
            <!--<div class="arrow"></div>-->
            <div class="icon">
              <span class="ico-book"></span>
            </div>                    
            <div class="name">Documents</div>
          </a>          
        </li> 
        <!--               
        <li>
          <a href="#" class="button green">
            <div class="arrow"></div>
            <div class="icon">
              <span class="ico-pen-2"></span>
            </div>                    
            <div class="name">News</div>
          </a>                
          <ul class="sub">
            <li><%= link_to "Envoi", "#" %></li>
            <li><%= link_to "Historique", "#" %></li>
            <li><%= link_to "Statistiques", "#" %></li>
          </ul>                    
        </li>                                               
        <li>
          <a href="#" class="button dblue">
            <div class="arrow"></div>
            <div class="icon">
              <span class="ico-layout-7"></span>
            </div>                    
            <div class="name">Abonnés</div>
          </a> 
          <ul class="sub">
            <li><a href="tables.html">Suspendre</a></li>
            <li><a href="tables_dynamic.html">Rechercher</a></li>
          </ul>                                        
        </li>
        <li>
          <a href="statistic.html" class="button red">
            <div class="icon">
              <span class="ico-chart-4"></span>
            </div>                    
            <div class="name">Paramètres</div>
          </a>                
        </li> -->                                
        <li>
          <div class="user">
            
            <!--<%= image_tag("examples/users/dmitry_m.jpg", align: "left") %>-->
            <a href="#" class="name">
              <span><%= current_user.full_name %></span>
              <span class="cblue"><%= current_user.profile %></span>
              <span class="sm"><%= current_user.show_qualification %></span>
            </a>
          </div>
          <div class="buttons">
            <!--<div class="sbutton green navButton">
              <a href="#"><span class="ico-align-justify"></span></a>
            </div>-->
            <div class="sbutton blue">
              <%= link_to "<span class='ico-off'></span>".html_safe, destroy_user_session_path, :method => :delete %>
           
            </div>                        
          </div>
        </li>               
      </ul>
      <!------------------------------------------ Navigation ----------------------------------->
      
      <!------------------------------------------ Content ----------------------------------->
      <div class = "content">
      	<%= yield %>
      </div>
      <!------------------------------------------ Content ----------------------------------->
      
		</div>
		<!------------------------------------------ Body ----------------------------------->
		  
	</div>
		

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyProfiler</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<% if user_signed_in? %>	
	<div style = "float:right;">
		<p>
			<%= current_user.short_profile %> 
			<%= link_to "Dashboard", administrator_dashboard_path %> |  
			<%= link_to "Profile", edit_user_profile_path(current_user.id) %> | 
			<%= link_to "Logout", destroy_user_session_path, :method =>  :delete %> |
			<%= link_to "Search", search_user_path %>
		</p>
	</div>
<% end %>


<%= yield %>

</body>
</html>

app/views/layouts/sessions.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Arci</title>
  <%= stylesheet_link_tag    "stylesheets", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "plugins/jquery/jquery-1.9.1.min", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "plugins/jquery/jquery-ui-1.10.1.custom.min", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "plugins/jquery/jquery-migrate-1.1.1.min", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "plugins/jquery/globalize", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "plugins/other/excanvas", "data-turbolinks-track" => true %>
  
  <%= javascript_include_tag "plugins/other/jquery.mousewheel.min", "data-turbolinks-track" => true %>
  
  <%= javascript_include_tag "plugins/bootstrap/bootstrap.min", "data-turbolinks-track" => true %>    
  
  <%= javascript_include_tag "plugins/cookies/jquery.cookies.2.2.0.min", "data-turbolinks-track" => true %> 
  
  <%= javascript_include_tag "plugins/jflot/jquery.flot", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "plugins/jflot/jquery.flot.stack", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "plugins/jflot/jquery.flot.pie", "data-turbolinks-track" => true %>
  
  <%= javascript_include_tag "plugins/sparklines/jquery.sparkline.min", "data-turbolinks-track" => true %>
  
  <%= javascript_include_tag "plugins/mcustomscrollbar/jquery.mCustomScrollbar.min", "data-turbolinks-track" => true %>
  
  <%= javascript_include_tag "plugins/uniform/jquery.uniform.min", "data-turbolinks-track" => true %>
  
  <%= javascript_include_tag "plugins/shbrush/XRegExp", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "plugins/shbrush/shCore", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "plugins/shbrush/shBrushXml", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "plugins/shbrush/shBrushJScript", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "plugins/shbrush/shBrushCss", "data-turbolinks-track" => true %>   
  
  <%= javascript_include_tag "plugins", "data-turbolinks-track" => true %> 
  <%= javascript_include_tag "charts", "data-turbolinks-track" => true %> 
  
  <%= javascript_include_tag "actions", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body>
	<div class = "login">		
    <%= yield %>	  
	</div>
</body>
</html>